version: "3.3"
services:
  app-dev:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 8001:8000
    environment:
      TZ: "America/Chicago"
      READ_ONLY: "false"
    volumes:
      - ./:/app/