version: "3.3"
services:
  app:
    build: ./
    ports:
      - 8001:8000
    environment:
      TZ: "America/Chicago"
      READ_ONLY: "true"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
