# Start: docker compose -f docker-compose-read-only.yaml up -d --build
# Logs: docker compose -f docker-compose-read-only.yaml logs --follow --tail 1000
# Stop: docker compose -f docker-compose-read-only.yaml down

version: "3.3"
services:
  read-only:
    build: ./
    ports:
      - 8002:8000
    environment:
      TZ: "America/Chicago"
      READ_ONLY: "true"
      DB_PATH: "../data/demo.db"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
