# docker compose -f docker-compose-read-only.yaml up

version: "3.3"
services:
  read-only:
    build: ./
    ports:
      - 8000:8000
    environment:
      TZ: "America/Chicago"
      READ_ONLY: "false"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
