# Start: docker compose -f docker-compose-dev.yaml up
# Logs: docker compose -f docker-compose-dev.yaml logs --follow --tail 1000
# Stop: docker compose -f docker-compose-dev.yaml down

services:
  dev:
    image: cosmtrek/air
    working_dir: /app/src
    ports:
      - 8001:8000
    environment:
      TZ: "America/Chicago"
      READ_ONLY: "false"
      DB_PATH: "../data/dev.db"
      PASSWORD: "password"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./public:/app/public
