# Start: docker compose up -d --build
# Logs: docker compose logs --follow --tail 1000
# Stop: docker compose down

services:
  app:
    build: ./
    ports:
      - 8000:8000
    environment:
      TZ: "America/Chicago"
      READ_ONLY: "false"
      PASSWORD: "password"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
