# docker compose up --build

version: "3.3"
services:
  app:
    build: ./
    ports:
      - 8000:8000
    environment:
      TZ: "America/Chicago"
      READ_ONLY: "false"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
