DROP TABLE IF EXISTS tracker_1;
DROP TABLE IF EXISTS tracker_2;
DROP TABLE IF EXISTS tracker_3;

DROP TABLE IF EXISTS option;
DROP TABLE IF EXISTS number;
DROP TABLE IF EXISTS field;
DROP TABLE IF EXISTS tracker;
